version: '3.8'
services:

  web:
    build: ./
    command: python expences/manage.py runserver 0.0.0.0:8000
    environment:
      SQL_HOST: db
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.en

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data/pgdata:/var/lib/postgresql/data/pgdata


