# Generated by Django 3.1.2 on 2020-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='kind',
            field=models.CharField(default='', max_length=64),
        ),
    ]
