# Generated by Django 3.1.2 on 2020-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testmodel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
