# Generated by Django 3.1.2 on 2020-11-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_anothertestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherTestModel',
        ),
    ]
